trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Create the file in the artifact staging directory
- script: |
    echo 'testing file to copy to ec2' > $BUILD_ARTIFACTSTAGINGDIRECTORY/file-to-ec2.txt
  displayName: 'Create test file'

# Step 2: Publish the staging directory as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'ec2File'

