trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Create the file
- script: |
    echo 'testing file to copy to ec2' > file-to-ec2.txt
  displayName: 'Create test file'

# Step 2: Publish the file as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'file-to-ec2.txt'   # file you created
    artifact: 'ec2File'             # artifact name shown in UI

