trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Create file in artifact staging directory
- script: |
    echo 'testing file to copy to ec2' > $(Build.ArtifactStagingDirectory)/file-to-ec2.txt
  displayName: 'Create test file'

# Step 2: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'ec2File'

# Step 3: Download artifact
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'ec2File'
    path: '$(Pipeline.Workspace)'

# Step 4: Download SSH private key from Secure Files
- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'azure.pem'   # must match the name in Secure Files

# Step 5: Setup SSH key
- script: |
    mkdir -p ~/.ssh
    cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa
  displayName: 'Setup SSH key'

# Step 6: Copy file to EC2
- script: |
    echo "Copying file to EC2..."
    ls -l $(Pipeline.Workspace)/ec2File
    chmod 700 StrictHostKeyChecking=no \  # <-- debug: list files first
    scp -o StrictHostKeyChecking=no \
        $(Pipeline.Workspace)/ec2File/file-to-ec2.txt \
        ec2-user@3.87.158.38:/home/ec2-user/
  displayName: 'Copy file to EC2'
